#!/usr/bin/env bash
# script sweet and short to fix problem, careful we stop with kill -9
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill -9 `cat /run/nginx.pid`
