#!/usr/bin/env bash
# init script control over the daemon
# variables $0 $1 are like argv
. /lib/lsb/init-functions

start() {
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
}

stop() {
    pkill -f manage_my_process &
    rm -f /var/run/my_process.pid
}
case "$1" in
    start)
	echo "manage_my_process started"
	start
	;;
    stop)
	echo "manage_my_process stopped"
	stop
	;;
    restart)
	echo "manage_my_process restarted"
	stop
	start
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0
