#!/usr/bin/env bash
# config ufw in the server in order to put a Firewall or protection
# install the ufw
sudo apt -y update
sudo apt-get install -y ufw
# block all incoming traffic but allow the outcoming one
sudo ufw default deny incoming
sudo ufw default allow outgoing
# first off all allow the ssh = 22 BEFORE the firewall
sudo ufw allow 22
# enable firewall
sudo ufw enable
# enable incoming for https=443 and http=80
# we can also type sudo uft allow http or sudo allow https
sudo ufw allow 443
sudo ufw allow 80
# if you wanna check the configuration
# run: sudo ufw status numbered
