#!/usr/bin/env bash
# change ip of localhost to 127.0.0.2
# change ip of facebook.com to 8.8.8.8
sudo cp /etc/hosts new-hosts
sed -i "s/127.0.0.1/127.0.0.2/" new-hosts
echo "8.8.8.8      facebook.com" >> new-hosts
sudo cp -f new-hosts /etc/hosts
